### ISSUE TITLE
eval coderef error

### ISSUE THREAD

**Issue by niumang** [jsober/Coro-ProcessPool#1]
Hi，guy,
when i used this pool to process http request,I found this error:

```
use Coro::ProcessPool;                                                          
use 5.010;                                                                      
use YAML 'Dump';                                                                
use Mojo::UserAgent;                                                            

my $ua = Mojo::UserAgent->new;                                                  
say $ua->get('m.hupu.com')->res->code;                                          
my $pool = Coro::ProcessPool->new(                                              
    max_procs => 4,                                                             
    max_reqs  => 100,                                                           
);                                                                              

my $double = sub {                                                              
    $ua->get(                                                                   
        'hoopchina.com' => sub {                                                
            say $_[1]->res->code;                                               
        }                                                                       
    );                                                                          
    return 1;                                                                   
};                                                                              

# Defer waiting for result                                                      
my %deferred = map { $_ => $pool->defer( $double, [$_] ) } ( 1 .. 1000 );       
foreach my $i ( keys %deferred ) {                                              
    print "$i = " . $deferred{$i}->() . "\n";                                   
}                                                                               

$pool->shutdown; 
```

302
Can't call method "get" on an undefined value at (eval 85) line 10.
 at /usr/local/share/perl/5.14.2/Coro/ProcessPool.pm line 97.
 at /usr/local/lib/perl/5.14.2/Coro/AnyEvent.pm line 361.

shell returned 9,how to resolve this,does this module not support closure?

**Comment by sysread** [comment]
This is because $ua is an external variable. In a normal process, it 
would be closed over by $double. However, because Coro::ProcessPool has 
to pass the data to another process, the stack is left behind. Any 
variables needed by the code ref must either be passed in as arguments 
or created from within the code ref itself. Try it like this:

my $double = sub {
   use Mojo::UserAgent;
   my $ua = Mojo::UserAgent->new;
   $ua->get('hoopchina.com' => sub { ... });
}

Or, by passing $ua as an argument to $double.

舌尖上的牛氓 wrote:

> Hi，guy,
> when i used this pool to process http request,I found this error:
> 
> |use Coro::ProcessPool;
> use 5.010;
> use YAML 'Dump';
> use Mojo::UserAgent;
> 
> my $ua = Mojo::UserAgent->new;
> say $ua->get('m.hupu.com')->res->code;
> my $pool = Coro::ProcessPool->new(
>      max_procs =>  4,
>      max_reqs  =>  100,
> );
> 
> my $double = sub {
>      $ua->get(
>          'hoopchina.com' =>  sub {
>              say $_[1]->res->code;
>          }
>      );
>      return 1;
> };
> 
> # Defer waiting for result
> 
> my %deferred = map { $_ =>  $pool->defer( $double, [$_] ) } ( 1 .. 1000 );
> foreach my $i ( keys %deferred ) {
>      print "$i = " . $deferred{$i}->() . "\n";
> }
> 
> $pool->shutdown;
> |
> 
> 302
> Can't call method "get" on an undefined value at (eval 85) line 10.
> at /usr/local/share/perl/5.14.2/Coro/ProcessPool.pm line 97.
> at /usr/local/lib/perl/5.14.2/Coro/AnyEvent.pm line 361.
> 
> shell returned 9,how to resolve this,does this module not support closure?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsober/Coro-ProcessPool/issues/1.

## 

Jeff Ober
Old programmers don't die; they just parse on...

**Comment by sysread** [comment]
One other thing - if you are just trying to do multiple downloads at a 
time, I suggest you look into Coro and Coro::LWP. This will allow you to 
perform multiple HTTP requests in a single process in the background 
with less overhead in memory and context switching.

舌尖上的牛氓 wrote:

> Hi，guy,
> when i used this pool to process http request,I found this error:
> 
> |use Coro::ProcessPool;
> use 5.010;
> use YAML 'Dump';
> use Mojo::UserAgent;
> 
> my $ua = Mojo::UserAgent->new;
> say $ua->get('m.hupu.com')->res->code;
> my $pool = Coro::ProcessPool->new(
>      max_procs =>  4,
>      max_reqs  =>  100,
> );
> 
> my $double = sub {
>      $ua->get(
>          'hoopchina.com' =>  sub {
>              say $_[1]->res->code;
>          }
>      );
>      return 1;
> };
> 
> # Defer waiting for result
> 
> my %deferred = map { $_ =>  $pool->defer( $double, [$_] ) } ( 1 .. 1000 );
> foreach my $i ( keys %deferred ) {
>      print "$i = " . $deferred{$i}->() . "\n";
> }
> 
> $pool->shutdown;
> |
> 
> 302
> Can't call method "get" on an undefined value at (eval 85) line 10.
> at /usr/local/share/perl/5.14.2/Coro/ProcessPool.pm line 97.
> at /usr/local/lib/perl/5.14.2/Coro/AnyEvent.pm line 361.
> 
> shell returned 9,how to resolve this,does this module not support closure?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsober/Coro-ProcessPool/issues/1.

## 

Jeff Ober
Old programmers don't die; they just parse on...

**Comment by niumang** [comment]
thanks for your response,i got it.

**Comment by niumang** [comment]
by the way,i test code again,when use 'require',it works, not 'use'

**Comment by sysread** [comment]
Awesome. Glad to hear it.

舌尖上的牛氓 wrote:

> by the way,i test code again,when use 'require',it works, not 'use'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsober/Coro-ProcessPool/issues/1#issuecomment-32037933.

## 

Jeff Ober
Old programmers don't die; they just parse on...
